# SoG bloomcast configuration file

infile: 2012_bloomcast_infile

climate:
  url: http://www.climate.weatheroffice.gc.ca/climateData/bulkdata_e.html
  params:
    timeframe: 1        # Daily
    Prov: BC
    format: xml
  meteo:
    station_id: 889     # YVR
    quantities:
      - air_temperature
      - relative_humidity
      - cloud_fraction
    cloud_fraction_mapping: cloud_fraction_mapping.yaml  # file containing mapping
  wind:
    station_id: 6831    # Sandheads
